version: 2

jobs:
  build:
    working_directory: ~/maelstrom
    docker:
      # Use dev image for XDMF interface support
      # - image: quay.io/fenicsproject/stable:current
      - image: quay.io/fenicsproject/dev
        user: fenics
        environment:
          LD_LIBRARY_PATH: ~/local/lib
          CMAKE_PREFIX_PATH: ~/local
    steps:
      - run: sudo apt update
      - run: sudo apt install -y git
      - run: sudo -H pip3 install matplotlib pytest pytest-cov
      - checkout
      # The actual test
      - run: PYTHONPATH=$PWD:$PYTHONPATH pytest tests/ --cov maelstrom
      # submit to codecov
      - run: sudo apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
